exports.STATE_PENDING = 0;
exports.STATE_PROCESSING = 1;
exports.STATE_FINISHED = 2;

exports.WITHDRAW_NEW = 0;
exports.WITHDRAW_FINISHED_SUCCESS = 1;
exports.WITHDRAW_FINISHED_FAILED = -1;
exports.WITHDRAW_WAITING_SEND_WALLET = 2;
exports.WITHDRAW_WAITING_WALLET_PROCESS = 3;

exports.DEPOSIT_PENDING = 0;
exports.DEPOSIT_SUCCESS = 1;

exports.TIME_EXPIRE_USER = 3600 * 24;

exports.TYPE_TRANSFER = {
    CREDIT: 'CREDIT',
    RETURN: 'RETURN'
}
exports.TYPE_ACCOUNT = {
    NORMAL: 'NORMAL',
    MERCHANT: 'MERCHANT'
}
